#!/usr/bin/env python3
"""Generate per-tool agent configuration from the repo's single sources of truth.

Sources (edit these):
    AGENTS.md, notebooks/AGENTS.md, results/AGENTS.md   instructions
    .agents/skills/<name>/SKILL.md (+ files)              portable skills
    harness/mcp.json                                      MCP servers
    harness/manifest.json                                 which tool reads what, where

Usage:
    python harness/sync.py            write generated files, remove stale ones
    python harness/sync.py --check    exit 1 if anything is missing, stale or edited by hand
    python harness/sync.py --list     print every generated path

Standard library only, so it runs in any agent sandbox or CI image.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "harness" / "manifest.json"
MD_HEADER = (
    "<!-- GENERATED by harness/sync.py from {src}. Do not edit this file: "
    "edit {src} and run `python harness/sync.py`. -->\n\n"
)
CODEX_BEGIN = "# >>> harness/sync.py: mcp (generated from harness/mcp.json) >>>"
CODEX_END = "# <<< harness/sync.py: mcp <<<"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def frontmatter(skill_md: str) -> dict:
    """Minimal YAML-frontmatter reader for `key: value` lines (Agent Skills format)."""
    match = re.match(r"^---\n(.*?)\n---\n", skill_md, re.S)
    if not match:
        return {}
    out = {}
    for line in match.group(1).splitlines():
        if ":" in line and not line.startswith((" ", "\t", "#")):
            key, value = line.split(":", 1)
            out[key.strip()] = value.strip().strip('"').strip("'")
    return out


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


# ---------------------------------------------------------------------------
# planning: compute every generated file in memory
# ---------------------------------------------------------------------------

def plan(manifest: dict) -> tuple[dict[str, str], set[str]]:
    """Return ({relative_path: content}, {owned directories})."""
    files: dict[str, str] = {}
    owned: set[str] = set()

    sources = [ROOT / s for s in manifest["instruction_sources"]]
    for src in sources:
        if not src.exists():
            raise SystemExit(f"missing instruction source: {rel(src)}")

    # 1. Instruction files that sit next to each AGENTS.md (CLAUDE.md, GEMINI.md, ...)
    for target in manifest.get("instruction_targets", []):
        for src in sources:
            out = src.parent / target["filename"]
            header = MD_HEADER.format(src=rel(src))
            if target["mode"] == "import":
                body = f"@{src.name}\n"
                if src.parent == ROOT and target.get("extra"):
                    body += "\n" + target["extra"]
            elif target["mode"] == "copy":
                body = read(src)
            else:
                raise SystemExit(f"unknown instruction mode {target['mode']!r}")
            files[rel(out)] = header + body

    # 2. Rule directories (one file per AGENTS.md, scoped by path)
    for target in manifest.get("rules_targets", []):
        rule_dir = ROOT / target["dir"]
        owned.add(rel(rule_dir))
        for index, src in enumerate(sources):
            scope = rel(src.parent) if src.parent != ROOT else ""
            name = f"{index:02d}-{scope.replace('/', '-') or 'project'}.md"
            preface = f"Applies when working on files under `{scope}/`.\n\n" if scope else ""
            files[rel(rule_dir / name)] = MD_HEADER.format(src=rel(src)) + preface + read(src)

    # 3. Skills: mirror .agents/skills/<name>/** into each tool's skills dir
    skills_root = ROOT / manifest["skills_source"]
    skills = sorted(p for p in skills_root.iterdir() if (p / "SKILL.md").is_file())
    for target in manifest.get("skills_targets", []):
        tdir = ROOT / target["dir"]
        owned.add(rel(tdir))
        for skill in skills:
            for f in sorted(skill.rglob("*")):
                if f.is_file() and "__pycache__" not in f.parts:
                    files[rel(tdir / skill.name / f.relative_to(skill))] = read(f)

    # 4. Slash-command / workflow shims that point back at the canonical skill
    for target in manifest.get("command_targets", []):
        cdir = ROOT / target["dir"]
        owned.add(rel(cdir))
        for skill in skills:
            meta = frontmatter(read(skill / "SKILL.md"))
            description = meta.get("description", skill.name).replace("\n", " ")
            files[rel(cdir / f"{skill.name}.md")] = target["template"].format(
                name=skill.name, description=description
            )

    # 5. MCP servers (only when harness/mcp.json declares any)
    servers = json.loads(read(ROOT / manifest["mcp_source"])).get("servers", {})
    if servers:
        for target in manifest.get("mcp_targets", []):
            path = ROOT / target["path"]
            files[rel(path)] = render_mcp(target["format"], servers, path)

    return files, owned


def render_mcp(fmt: str, servers: dict, path: Path) -> str:
    def is_remote(s):
        return "url" in s

    if fmt == "claude":
        out = {}
        for name, s in servers.items():
            out[name] = (
                {"type": "http", "url": s["url"], **({"headers": s["headers"]} if s.get("headers") else {})}
                if is_remote(s)
                else {"command": s["command"], "args": s.get("args", []), **({"env": s["env"]} if s.get("env") else {})}
            )
        return json.dumps({"mcpServers": out}, indent=2) + "\n"

    if fmt == "gemini":
        existing = json.loads(read(path)) if path.exists() else {}
        out = {}
        for name, s in servers.items():
            out[name] = (
                {"httpUrl": s["url"], **({"headers": s["headers"]} if s.get("headers") else {})}
                if is_remote(s)
                else {"command": s["command"], "args": s.get("args", []), **({"env": s["env"]} if s.get("env") else {})}
            )
        existing["mcpServers"] = out
        return json.dumps(existing, indent=2) + "\n"

    if fmt == "opencode-merge":
        existing = json.loads(read(path)) if path.exists() else {"$schema": "https://opencode.ai/config.json"}
        out = {}
        for name, s in servers.items():
            out[name] = (
                {"type": "remote", "url": s["url"], **({"headers": s["headers"]} if s.get("headers") else {})}
                if is_remote(s)
                else {"type": "local", "command": [s["command"], *s.get("args", [])],
                      **({"environment": s["env"]} if s.get("env") else {})}
            )
        existing["mcp"] = out
        return json.dumps(existing, indent=2) + "\n"

    if fmt == "codex-toml":
        def q(v):
            return json.dumps(v)  # TOML basic strings are compatible with JSON strings

        lines = [CODEX_BEGIN]
        for name, s in servers.items():
            lines.append(f"[mcp_servers.{name}]")
            if is_remote(s):
                lines.append(f"url = {q(s['url'])}")
            else:
                lines.append(f"command = {q(s['command'])}")
                lines.append("args = [" + ", ".join(q(a) for a in s.get("args", [])) + "]")
                if s.get("env"):
                    lines.append("env = { " + ", ".join(f"{k} = {q(v)}" for k, v in s["env"].items()) + " }")
            lines.append("")
        lines.append(CODEX_END)
        block = "\n".join(lines) + "\n"
        existing = read(path) if path.exists() else ""
        if CODEX_BEGIN in existing:
            pre, rest = existing.split(CODEX_BEGIN, 1)
            post = rest.split(CODEX_END, 1)[1].lstrip("\n")
            return pre + block + post
        return (existing.rstrip("\n") + "\n\n" if existing else "") + block

    raise SystemExit(f"unknown mcp format {fmt!r}")


# ---------------------------------------------------------------------------
# apply / check
# ---------------------------------------------------------------------------

def stale_files(files: dict[str, str], owned: set[str]) -> list[str]:
    stale = []
    for d in owned:
        base = ROOT / d
        if base.exists():
            for f in base.rglob("*"):
                if f.is_file() and "__pycache__" not in f.parts and rel(f) not in files:
                    stale.append(rel(f))
    return sorted(stale)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report drift, write nothing")
    parser.add_argument("--list", action="store_true", help="list generated paths")
    args = parser.parse_args()

    manifest = json.loads(read(MANIFEST))
    files, owned = plan(manifest)
    stale = stale_files(files, owned)

    if args.list:
        print("\n".join(sorted(files)))
        return 0

    drift = [p for p, c in files.items() if not (ROOT / p).exists() or read(ROOT / p) != c]

    if args.check:
        for p in drift:
            print(f"DRIFT  {p}  (missing or edited by hand)")
        for p in stale:
            print(f"STALE  {p}  (no longer produced by any source)")
        if drift or stale:
            print("\nRun `python harness/sync.py` and commit the result.")
            return 1
        print(f"harness in sync: {len(files)} generated files")
        return 0

    for p in drift:
        out = ROOT / p
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(files[p], encoding="utf-8", newline="\n")
        if out.suffix in {".py", ".sh"}:
            out.chmod(0o755)
        print(f"wrote  {p}")
    for p in stale:
        (ROOT / p).unlink()
        print(f"removed {p}")
    for d in sorted(owned, key=len, reverse=True):  # prune empty dirs left behind
        for sub in sorted((ROOT / d).rglob("*"), key=lambda x: len(x.parts), reverse=True) if (ROOT / d).exists() else []:
            if sub.is_dir() and not any(sub.iterdir()):
                sub.rmdir()
    print(f"done: {len(drift)} written, {len(stale)} removed, {len(files)} generated files total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
