#!/usr/bin/env python3
"""PreToolUse guard: block agent edits to immutable, append-only or generated paths.

This file is wired into Claude Code via .claude/settings.json. Any tool that can run a
pre-edit command can reuse it: it reads the hook JSON on stdin, or takes a path as argv[1].
Exit code 2 blocks the edit and sends the stderr message back to the agent.
The same rules are enforced for every tool in CI by `harness/check.py --base`.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GENERATED = re.compile(
    r"^((notebooks/|results/)?CLAUDE\.md|\.claude/skills/.*|\.agents/workflows/.*|\.opencode/commands/.*)$"
)


def verdict(path_str: str) -> str | None:
    try:
        path = Path(path_str).resolve()
        rel = path.relative_to(ROOT).as_posix()
    except (ValueError, OSError):
        return None  # outside the repo: not our concern
    if GENERATED.match(rel):
        return (f"{rel} is generated by harness/sync.py. Edit the source (AGENTS.md or "
                ".agents/skills/…) and run `python harness/sync.py`.")
    if rel.startswith("results/runs/") and path.exists():
        return (f"{rel} is an imported run artefact and is immutable. Add a new file, "
                "or record the problem in a new docs/audits/ entry.")
    if re.match(r"^docs/audits/\d{4}-\d{2}-\d{2}_.*\.md$", rel) and path.exists():
        return f"{rel} is a dated audit and is append-only. Write a new dated audit instead."
    return None


def main() -> int:
    if len(sys.argv) > 1:
        paths = sys.argv[1:]
    else:
        try:
            payload = json.load(sys.stdin)
        except json.JSONDecodeError:
            return 0
        tool_input = payload.get("tool_input", {}) or {}
        paths = [tool_input.get(k) for k in ("file_path", "notebook_path", "path") if tool_input.get(k)]
    for p in paths:
        message = verdict(p)
        if message:
            print(f"Blocked by harness/hooks/protect_paths.py: {message}", file=sys.stderr)
            return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
